#!/bin/bash

# 0 - installed
# 1 - not installed
# 2 - not linked
# 3 - doesn't exist

echo -n "$1 - "
if [ -d /root/src/"$1" ]
then
  echo "not installed"
  exit 1
else
  if [ -d /root/src/installed/"$1" ]
  then
    echo "Installed"
    exit 0
  else
    LNK=$(slackfindexact "$1")
    if [ -d "$LNK" ]
    then
      echo "not linked - $LNK"
      exit 2
    else
      echo "DOESN'T EXIST"
      exit 3
    fi
  fi
fi
